version: '1'
services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      - ./:/opt/drupal
      - ./config/sync:/var/www/html/config/sync
    depends_on:
      - db
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=drupal

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
