version: '1'
services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
    # /var/www/html is a sym link to /opt/drupal/web so make sure this mapping is correct
      # - ./:/opt/drupal
      # - ./custom_assets:/opt/drupal/web/modules/custom
      # - ./custom_themes:/web/themes/custom TODO
      # - ./custom_assets:/web/modules/custo
    depends_on:
      - db
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=drupal

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal

volumes:
  # db_data:
  # custom_assets:
