<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_create()
 */
function pods_group_entity_create(EntityInterface $entity) {
  if ($entity->bundle() && $entity->bundle() === 'project') {

    \Drupal::logger('example from hook entity create')
    ->info('Entity created: @label', [
      '@label' => $entity
      ->bundle(),
    ]);
    // TODO: trigger creation of corresponding Group here
  }
}
